import type {
  DocumentType,
  Shipment,
  ShipmentDocument,
  ValidationIssue,
} from "./types";
import { emit } from "./events";

/**
 * Document Intelligence.
 *
 * Generates the paper trail from the shipment object (single source of truth
 * means documents can never disagree with the system — only with each other
 * when they arrive from outside), and cross-validates data between documents
 * to detect errors automatically.
 */

export const DOCUMENT_LABELS: Record<DocumentType, string> = {
  COMMERCIAL_INVOICE: "Commercial invoice",
  PACKING_LIST: "Packing list",
  BILL_OF_LADING: "Bill of lading",
  AIR_WAYBILL: "Air waybill",
  DELIVERY_ORDER: "Delivery order",
  CUSTOMS_DECLARATION: "Customs declaration",
  CERTIFICATE_OF_ORIGIN: "Certificate of origin",
};

let docSeq = 0;

export function documentSeq(): number {
  return docSeq;
}

export function restoreDocumentSeq(seq: number): void {
  docSeq = seq;
}

export function requiredDocuments(shipment: Shipment): DocumentType[] {
  const base: DocumentType[] = ["COMMERCIAL_INVOICE", "PACKING_LIST", "CUSTOMS_DECLARATION"];
  base.push(shipment.mode === "AIR" ? "AIR_WAYBILL" : "BILL_OF_LADING");
  if (shipment.incoterm === "DDP" || shipment.incoterm === "DAP") base.push("DELIVERY_ORDER");
  if (shipment.cargo.value > 20_000) base.push("CERTIFICATE_OF_ORIGIN");
  return base;
}

export function generateDocuments(shipment: Shipment, at?: string): ShipmentDocument[] {
  const docs = requiredDocuments(shipment).map((type): ShipmentDocument => ({
    id: `doc-${++docSeq}`,
    shipmentId: shipment.id,
    type,
    status: "GENERATED",
    autoGenerated: true,
    issues: [],
    createdAt: at ?? new Date().toISOString(),
  }));
  emit(
    "document.generated",
    shipment.id,
    `${docs.length} documents generated from shipment object`,
    "INFO",
    at
  );
  return docs;
}

/**
 * Cross-document validation. In production each check compares extracted
 * values from the inbound paper against the shipment object; here we surface
 * the check catalogue with any pre-seeded discrepancies.
 */
export function validateDocuments(
  shipment: Shipment,
  docs: ShipmentDocument[],
  seededIssues: ValidationIssue[] = []
): ValidationIssue[] {
  const issues: ValidationIssue[] = [...seededIssues];
  const have = new Set(docs.map((d) => d.type));
  for (const required of requiredDocuments(shipment)) {
    if (!have.has(required)) {
      issues.push({
        severity: "ERROR",
        field: "document",
        message: `${DOCUMENT_LABELS[required]} missing for ${shipment.incoterm} ${shipment.mode} shipment`,
        documents: [required],
      });
    }
  }
  if (issues.some((i) => i.severity === "ERROR")) {
    emit(
      "document.validation_failed",
      shipment.id,
      `${issues.filter((i) => i.severity === "ERROR").length} validation error(s) across document set`,
      "WARNING"
    );
  }
  return issues;
}
