import { describe, expect, it } from "vitest";
import { priorityQueue } from "./priority";
import { answerQuery } from "./assistant";
import type {
  AgentAction,
  Customer,
  IntakeMessage,
  Invoice,
  Quote,
  Shipment,
  ShipmentDocument,
} from "./types";

const now = new Date("2026-07-02T12:00:00.000Z");
const iso = (offsetHours: number) => new Date(now.getTime() + offsetHours * 3600_000).toISOString();

const shipment: Shipment = {
  id: "ENG-2026-0900",
  ref: "priority test",
  state: "TRANSIT",
  customerId: "c1",
  origin: "SGSIN Singapore",
  destination: "USLAX Los Angeles",
  mode: "OCEAN",
  incoterm: "CIF",
  cargo: { commodity: "electronics", weightKg: 900, volumeCbm: 4, pieces: 4, hazardous: false, value: 90_000 },
  createdAt: iso(-72),
  stateEnteredAt: iso(-24),
  revenue: 6_000,
  cost: 5_000,
  hasOpenException: true,
  eta: { promised: iso(48), predicted: iso(96), deltaDays: 2, delayRisk: 0.6, drivers: ["congestion"] },
};

const escalation: AgentAction = {
  id: "a1", shipmentId: shipment.id, taskType: "BOOKING", levelUsed: 3,
  summary: "Booking held for approval", detail: "", confidence: 0.9,
  valueAtStake: 12_000, status: "AWAITING_APPROVAL", at: iso(-1),
};

const overdueInvoice: Invoice = {
  id: "INV-900", shipmentId: shipment.id, customerId: "c1", amount: 9_000,
  currency: "USD", issuedAt: iso(-30 * 24), dueAt: iso(-5 * 24), status: "OVERDUE",
  financingOffered: false,
};

const badDoc: ShipmentDocument = {
  id: "d1", shipmentId: shipment.id, type: "PACKING_LIST", status: "DRAFT",
  autoGenerated: false, createdAt: iso(-3),
  issues: [{ severity: "ERROR", field: "weightKg", message: "weight mismatch", documents: ["PACKING_LIST"] }],
};

const expiringQuote: Quote = {
  id: "Q-900", shipmentId: shipment.id, verdict: "PENDING", generatedInMs: 400, createdAt: iso(-40),
  options: [{
    id: "o1", mode: "OCEAN", carrier: "ONE", transitDays: 21, baseRate: 2000, surcharges: [],
    costTotal: 2000, margin: 400, marginPct: 20, sellTotal: 2400, winProbability: 0.7,
    validUntil: iso(8),
  }],
};

const freshIntake: IntakeMessage = {
  id: "m1", channel: "WHATSAPP", from: "Test Co", receivedAt: iso(-2), raw: "3 pallets", status: "NEW",
};

describe("escalation engine / priority queue", () => {
  const queue = priorityQueue({
    shipments: [shipment],
    invoices: [overdueInvoice],
    quotes: [expiringQuote],
    intake: [freshIntake],
    documents: [badDoc],
    actions: [escalation],
    now,
  });

  it("surfaces every category of human-needed work", () => {
    const kinds = queue.map((t) => t.kind);
    expect(kinds).toContain("APPROVAL");
    expect(kinds).toContain("EXCEPTION");
    expect(kinds).toContain("DOCUMENT");
    expect(kinds).toContain("COLLECTION");
    expect(kinds).toContain("QUOTE_EXPIRING");
    expect(kinds).toContain("INTAKE");
  });

  it("ranks the queue by score, highest first", () => {
    const scores = queue.map((t) => t.score);
    expect(scores).toEqual([...scores].sort((a, b) => b - a));
  });

  it("puts stuck cargo and agent hand-offs above paperwork and chasing", () => {
    const rank = (kind: string) => queue.findIndex((t) => t.kind === kind);
    expect(rank("EXCEPTION")).toBeLessThan(rank("COLLECTION"));
    expect(rank("APPROVAL")).toBeLessThan(rank("INTAKE"));
  });

  it("every task explains itself and links somewhere actionable", () => {
    for (const t of queue) {
      expect(t.why.length).toBeGreaterThan(5);
      expect(t.href.startsWith("/")).toBe(true);
      expect(t.score).toBeGreaterThanOrEqual(0);
      expect(t.score).toBeLessThanOrEqual(100);
    }
  });

  it("ignores quotes with more than 24h of validity left", () => {
    const relaxed = priorityQueue({
      shipments: [], invoices: [], intake: [], documents: [], actions: [],
      quotes: [{ ...expiringQuote, options: [{ ...expiringQuote.options[0], validUntil: iso(40) }] }],
      now,
    });
    expect(relaxed).toHaveLength(0);
  });
});

describe("conversational assistant", () => {
  const customers: Customer[] = [{
    id: "c1", name: "Pacific Components Inc", country: "USA",
    creditScore: 91, avgDaysToPay: 18, churnRisk: 0.05, acceptsSpeedPremium: true,
  }];
  const ctx = {
    shipments: [shipment],
    invoices: [overdueInvoice],
    quotes: [expiringQuote],
    intake: [freshIntake],
    customers,
    actions: [escalation] as const,
  };

  it("answers a direct shipment id lookup with state and risk", () => {
    const r = answerQuery("where is ENG-2026-0900?", ctx);
    expect(r.text).toContain("Transit");
    expect(r.text).toContain("+2d");
    expect(r.refs[0].href).toBe("/shipments/ENG-2026-0900");
  });

  it("reports overdue money", () => {
    const r = answerQuery("what's overdue?", ctx);
    expect(r.text).toContain("INV-900");
    expect(r.text).toContain("$9,000");
  });

  it("summarizes a customer's book", () => {
    const r = answerQuery("how is Pacific doing?", ctx);
    expect(r.text).toContain("Pacific Components Inc");
    expect(r.text).toContain("credit 91/100");
  });

  it("surfaces what needs approval", () => {
    const r = answerQuery("what needs my approval?", ctx);
    expect(r.text).toContain("Booking held for approval");
  });

  it("admits when a shipment doesn't exist instead of hallucinating", () => {
    const r = answerQuery("status of ENG-2026-9999", ctx);
    expect(r.text).toContain("don't have");
    expect(r.refs).toHaveLength(0);
  });

  it("offers its capabilities on an unrecognized query", () => {
    const r = answerQuery("sing me a sea shanty", ctx);
    expect(r.text).toContain("ENG-2026-0847");
  });
});
