/**
 * The Engine Room — domain types.
 *
 * The entire universe of the platform revolves around exactly one object:
 * THE SHIPMENT. Everything else in this file is either a component of a
 * shipment, an event emitted by a shipment, or a view derived from shipments.
 */

// ─── Lifecycle ────────────────────────────────────────────────────────────────

export const SHIPMENT_STATES = [
  "INQUIRY",
  "QUOTE",
  "BOOKING",
  "DOCUMENTATION",
  "TRANSIT",
  "CUSTOMS",
  "SETTLEMENT",
] as const;

export type ShipmentState = (typeof SHIPMENT_STATES)[number];

export type TransportMode = "OCEAN" | "AIR" | "LAND";

export type Incoterm =
  | "EXW" | "FCA" | "FAS" | "FOB" | "CFR" | "CIF" | "CPT" | "CIP" | "DAP" | "DPU" | "DDP";

// ─── Parties & cargo ─────────────────────────────────────────────────────────

export interface Customer {
  id: string;
  name: string;
  country: string;
  /** 0–100. Derived from payment history, disputes, tenure. */
  creditScore: number;
  avgDaysToPay: number;
  /** Probability [0,1] the customer churns in the next 90 days. */
  churnRisk: number;
  acceptsSpeedPremium: boolean;
}

export interface Cargo {
  commodity: string;
  hsCode?: string;
  weightKg: number;
  volumeCbm: number;
  pieces: number;
  hazardous: boolean;
  value: number; // USD
}

// ─── Quotes & pricing ────────────────────────────────────────────────────────

export interface SurchargeLine {
  code: string; // e.g. BAF, PSS, CAF
  name: string;
  amount: number; // USD
  reason: string;
}

export interface QuoteOption {
  id: string;
  mode: TransportMode;
  carrier: string;
  transitDays: number;
  baseRate: number;
  surcharges: SurchargeLine[];
  costTotal: number;
  margin: number; // USD added on top of cost
  marginPct: number;
  sellTotal: number;
  /** Model-estimated probability [0,1] this option wins at this price. */
  winProbability: number;
  validUntil: string; // ISO
}

export type QuoteVerdict = "PENDING" | "WON" | "LOST" | "EXPIRED";

export interface Quote {
  id: string;
  shipmentId: string;
  options: QuoteOption[];
  selectedOptionId?: string;
  verdict: QuoteVerdict;
  generatedInMs: number;
  createdAt: string;
}

// ─── Documents ───────────────────────────────────────────────────────────────

export type DocumentType =
  | "COMMERCIAL_INVOICE"
  | "PACKING_LIST"
  | "BILL_OF_LADING"
  | "AIR_WAYBILL"
  | "DELIVERY_ORDER"
  | "CUSTOMS_DECLARATION"
  | "CERTIFICATE_OF_ORIGIN";

export interface ValidationIssue {
  severity: "ERROR" | "WARNING";
  field: string;
  message: string;
  documents: DocumentType[];
}

export interface ShipmentDocument {
  id: string;
  shipmentId: string;
  type: DocumentType;
  status: "DRAFT" | "GENERATED" | "VALIDATED" | "SENT" | "SIGNED";
  autoGenerated: boolean;
  issues: ValidationIssue[];
  createdAt: string;
}

// ─── Finance ─────────────────────────────────────────────────────────────────

export interface Invoice {
  id: string;
  shipmentId: string;
  customerId: string;
  amount: number;
  currency: "USD";
  issuedAt: string;
  dueAt: string;
  status: "DRAFT" | "ISSUED" | "OVERDUE" | "PAID";
  financingOffered: boolean;
  financingAprPct?: number;
}

// ─── Tracking & prediction ───────────────────────────────────────────────────

export interface TrackingEvent {
  id: string;
  shipmentId: string;
  at: string;
  location: string;
  description: string;
  isException: boolean;
}

export interface EtaPrediction {
  promised: string;
  predicted: string;
  /** Positive = late, in days. */
  deltaDays: number;
  delayRisk: number; // [0,1]
  drivers: string[]; // human-readable factors
}

// ─── Intake ──────────────────────────────────────────────────────────────────

export type IntakeChannel = "WHATSAPP" | "EMAIL" | "VOICE_NOTE" | "PDF" | "IMAGE";

export interface ExtractedField<T> {
  value: T | null;
  confidence: number; // [0,1]
  source: string; // which fragment of the raw message it came from
}

export interface IntakeExtraction {
  origin: ExtractedField<string>;
  destination: ExtractedField<string>;
  commodity: ExtractedField<string>;
  weightKg: ExtractedField<number>;
  volumeCbm: ExtractedField<number>;
  pieces: ExtractedField<number>;
  incoterm: ExtractedField<Incoterm>;
  mode: ExtractedField<TransportMode>;
  neededBy: ExtractedField<string>;
  customerName: ExtractedField<string>;
  /** Mean confidence across populated fields. */
  overallConfidence: number;
}

export interface IntakeMessage {
  id: string;
  channel: IntakeChannel;
  from: string;
  receivedAt: string;
  raw: string;
  extraction?: IntakeExtraction;
  status: "NEW" | "PARSED" | "CONVERTED" | "REJECTED";
  shipmentId?: string;
  /** Which engine produced the extraction: the live LLM or the local parser. */
  parsedBy?: string;
}

// ─── The Agent ───────────────────────────────────────────────────────────────

/**
 * Autonomy is earned in four notches, per task type:
 *  1 SUGGEST — propose, human does it.
 *  2 DRAFT   — prepare the action, human sends it.
 *  3 APPROVE — execute after one-tap human approval.
 *  4 AUTO    — execute automatically, report after.
 */
export type AutonomyLevel = 1 | 2 | 3 | 4;

export type AgentTaskType =
  | "QUOTE"
  | "BOOKING"
  | "DOCUMENTS"
  | "CUSTOMER_UPDATE"
  | "EXCEPTION_HANDLING"
  | "COLLECTIONS";

export interface AutonomyGrant {
  taskType: AgentTaskType;
  level: AutonomyLevel;
  /** Successful actions completed at or above current level. */
  earnedOver: number;
  /** USD value above which the agent always escalates regardless of level. */
  valueCeiling: number;
}

export type AgentActionStatus =
  | "SUGGESTED"
  | "DRAFTED"
  | "AWAITING_APPROVAL"
  | "EXECUTED"
  | "ESCALATED"
  | "REJECTED";

export interface AgentAction {
  id: string;
  shipmentId: string;
  taskType: AgentTaskType;
  levelUsed: AutonomyLevel;
  summary: string;
  detail: string;
  confidence: number; // [0,1]
  valueAtStake: number; // USD
  status: AgentActionStatus;
  at: string;
  escalationReason?: string;
}

// ─── Trade Intelligence Graph ────────────────────────────────────────────────

export interface LaneStats {
  lane: string; // "CNSHA → NLRTM"
  origin: string;
  destination: string;
  mode: TransportMode;
  medianTransitDays: number;
  rateTrendPct: number; // week-over-week
  congestionIndex: number; // [0,1]
  customsDelayDays: number;
  demandIndex: number; // [0,1]
  observations: number;
}

export interface CarrierScore {
  carrier: string;
  mode: TransportMode;
  onTimePct: number;
  rollingRiskPct: number;
  docAccuracyPct: number;
  shipmentsScored: number;
}

// ─── Events (the nervous system) ─────────────────────────────────────────────

export type ShipmentEventType =
  | "shipment.created"
  | "shipment.state_changed"
  | "quote.generated"
  | "quote.accepted"
  | "booking.confirmed"
  | "document.generated"
  | "document.validation_failed"
  | "tracking.updated"
  | "tracking.exception"
  | "eta.revised"
  | "customs.cleared"
  | "invoice.issued"
  | "payment.received"
  | "agent.action"
  | "agent.escalated"
  | "graph.learned";

export interface ShipmentEvent {
  id: string;
  type: ShipmentEventType;
  shipmentId: string;
  at: string;
  summary: string;
  severity: "INFO" | "SUCCESS" | "WARNING" | "CRITICAL";
}

// ─── The night shift ─────────────────────────────────────────────────────────

export interface ShiftLogEntry {
  at: string;
  text: string;
  kind: "AUTO" | "HUMAN_QUEUED" | "INFO";
}

export interface ShiftReport {
  ranAt: string;
  windowHours: number;
  intakeParsed: number;
  quotesSent: number;
  bookingsMade: number;
  revenueBooked: number;
  docsGenerated: number;
  updatesSent: number;
  queuedForMorning: number;
  hoursEliminated: number;
  log: ShiftLogEntry[];
}

// ─── THE SHIPMENT ────────────────────────────────────────────────────────────

export interface Shipment {
  id: string; // ENG-2026-XXXX
  ref: string; // human-friendly
  state: ShipmentState;
  customerId: string;
  origin: string; // UN/LOCODE + city
  destination: string;
  mode: TransportMode;
  incoterm: Incoterm;
  cargo: Cargo;
  carrier?: string;
  vesselOrFlight?: string;
  neededBy?: string;
  createdAt: string;
  stateEnteredAt: string;
  /** Money view */
  revenue: number;
  cost: number;
  /** Live operational view */
  eta?: EtaPrediction;
  hasOpenException: boolean;
  /** Provenance */
  sourceIntakeId?: string;
}
