"use client";

import Link from "next/link";
import { useWorld } from "@/core/use-world";
import { DOCUMENT_LABELS } from "@/core/documents";
import { Mono, Panel, StatTile, timeAgo } from "@/components/ui";

export default function DocumentsPage() {
  const { world } = useWorld();
  const docs = [...world.documents].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const errorCount = docs.reduce((n, d) => n + d.issues.filter((i) => i.severity === "ERROR").length, 0);
  const warningCount = docs.reduce((n, d) => n + d.issues.filter((i) => i.severity === "WARNING").length, 0);
  const autoPct = docs.length ? Math.round((docs.filter((d) => d.autoGenerated).length / docs.length) * 100) : 0;

  return (
    <div className="space-y-5">
      <div>
        <Mono className="text-instr">Document intelligence</Mono>
        <h1 className="mt-1 text-2xl font-semibold uppercase tracking-wide">
          Paper that argues with itself, caught automatically.
        </h1>
        <p className="mt-1 max-w-2xl text-sm text-foam-soft">
          Documents are generated from the shipment object, so they can never disagree with the
          system — only with paper arriving from outside. Cross-validation catches that before
          customs does.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile label="Documents on file" value={String(docs.length)} />
        <StatTile label="Auto-generated" value={`${autoPct}%`} detail="human hours eliminated" tone="instr" />
        <StatTile label="Validation errors" value={String(errorCount)} tone={errorCount ? "danger" : "instr"} detail={errorCount ? "blocking cut-off" : "clean set"} />
        <StatTile label="Warnings" value={String(warningCount)} tone={warningCount ? "brass" : "foam"} />
      </div>

      <Panel title="Document ledger">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-line text-foam-soft">
              {["Document", "Shipment", "Status", "Origin", "Issues", "Age"].map((h, i) => (
                <th key={h} className={`py-2 font-mono font-normal uppercase tracking-[0.12em] ${i === 0 ? "px-4" : "px-2"}`}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {docs.map((doc) => (
              <tr key={doc.id} className="border-b border-line-soft align-top hover:bg-panel">
                <td className="px-4 py-2.5 text-foam">{DOCUMENT_LABELS[doc.type]}</td>
                <td className="px-2 py-2.5">
                  <Link href={`/shipments/${doc.shipmentId}`} className="font-mono text-instr hover:underline">
                    {doc.shipmentId}
                  </Link>
                </td>
                <td className="px-2 py-2.5">
                  <Mono className={doc.status === "DRAFT" ? "text-brass" : "text-instr"}>{doc.status}</Mono>
                </td>
                <td className="px-2 py-2.5 text-foam-soft">{doc.autoGenerated ? "engine" : "inbound"}</td>
                <td className="px-2 py-2.5">
                  {doc.issues.length === 0 ? (
                    <span className="text-foam-soft/50">—</span>
                  ) : (
                    doc.issues.map((issue) => (
                      <div
                        key={issue.message}
                        className={`mb-1 border-l-2 pl-2 text-[11px] ${issue.severity === "ERROR" ? "border-danger text-danger" : "border-brass text-brass"}`}
                      >
                        {issue.message}
                      </div>
                    ))
                  )}
                </td>
                <td className="px-2 py-2.5 text-foam-soft">{timeAgo(doc.createdAt)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Panel>
    </div>
  );
}
